'use client';

import {Box} from '@mui/material';
import {Inter} from 'next/font/google';
import React from 'react';

import CustomThemeProvider from '@/components/CustomThemeProvider';
import Footer from '@/components/Footer';
import Header from '@/components/Header';
import {Providers} from '@/redux/provider';

const inter = Inter({subsets: ['latin']});

export default function RootLayout({children}: {children: React.ReactNode}) {
  const logoText = 'SEARCH';
  const footerText = 'MorozArtDev • © 2023';

  return (
    <html lang='en'>
      <head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='./favicon.ico' />
      </head>
      <CustomThemeProvider>
        <Providers>
          <Box
            component='body'
            className={inter.className}
            sx={{
              display: 'flex',
              flexDirection: 'column',
              minHeight: '100vh',
            }}
          >
            <Header logoText={logoText} />
            <Box component='main' sx={{flexGrow: 1}}>
              {children}
            </Box>
            <Footer footerText={footerText} />
          </Box>
        </Providers>
      </CustomThemeProvider>
    </html>
  );
}
