'use client';

import createCache from '@emotion/cache';
import {CacheProvider} from '@emotion/react';
import {ThemeProvider as EmotionThemeProvider} from '@emotion/react';
import CssBaseline from '@mui/material/CssBaseline';
import {ThemeProvider} from '@mui/material/styles';
import {Inter} from 'next/font/google';
import React from 'react';

import theme from '../theme/theme';

import Footer from '@/components/Footer';
import Header from '@/components/Header';

const inter = Inter({subsets: ['latin']});
const cache = createCache({key: 'css', prepend: true});

export default function RootLayout({children}: {children: React.ReactNode}) {
  const logoText = 'Logo';
  const footerText = 'MorozArtDev • © 2023';

  return (
    <html lang='en'>
      <head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </head>
      <CacheProvider value={cache}>
        <EmotionThemeProvider theme={theme}>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <body className={inter.className}>
              <Header logoText={logoText} />
              <main>{children}</main>
              <Footer footerText={footerText} />
            </body>
          </ThemeProvider>
        </EmotionThemeProvider>
      </CacheProvider>
    </html>
  );
}
